version: "3.2"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567-4586:4567-4586"
      - "4592-4593:4592-4593"
      - "8055:8080"
    environment:
      - SERVICES=iam,lambda,dynamodb,apigateway,s3,sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
