version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - 5432:5432
    environment: 
      - TZ=GMT+2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080